name: Deploy Manual to Production Server

on:
    workflow_dispatch:
        inputs:
            image_tag:
                description: "Tag da imagem Docker para deploy. Se vazio, será usada a última publicada no ECR."
                required: false

jobs:
    deploy:
        name: Deploy to Server
        runs-on: ubuntu-latest
        steps:
            - name: Determine Image Tag
              id: define-image
              env:
                  AWS_REGION: ${{ secrets.AWS_REGION }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              run: |
                  IMAGE_TAG_INPUT="${{ github.event.inputs.image_tag }}"
                  if [ -n "$IMAGE_TAG_INPUT" ]; then
                    echo "Verificando se a imagem com tag '$IMAGE_TAG_INPUT' existe no ECR..."
                    IMAGE_EXISTS=$(aws ecr describe-images \
                      --repository-name kodus-web-prod \
                      --region $AWS_REGION \
                      --query "imageDetails[?contains(imageTags, '$IMAGE_TAG_INPUT')]" \
                      --output text)
                    if [ -z "$IMAGE_EXISTS" ]; then
                      echo "Imagem com a tag '$IMAGE_TAG_INPUT' não encontrada no ECR."
                      exit 1
                    fi
                    echo "Usando tag: $IMAGE_TAG_INPUT"
                    echo "IMAGE_TAG=$IMAGE_TAG_INPUT" >> $GITHUB_ENV
                  else
                    echo "Buscando a tag mais recente no ECR..."
                    LAST_TAG=$(aws ecr describe-images \
                      --repository-name kodus-web-prod \
                      --region $AWS_REGION \
                      --query "sort_by(imageDetails, &imagePushedAt)[-1].imageTags[0]" \
                      --output text)
                    if [ -z "$LAST_TAG" ]; then
                      echo "Nenhuma imagem encontrada no ECR."
                      exit 1
                    fi
                    echo "Última tag encontrada: $LAST_TAG"
                    echo "IMAGE_TAG=$LAST_TAG" >> $GITHUB_ENV
                  fi

            - name: Get Runner IP
              run: |
                  ip=$(curl -s https://ipinfo.io/ip)
                  echo "::add-mask::$ip"
                  echo "runner_ip=$ip" >> $GITHUB_ENV

            - name: Add Runner IP to Security Group
              run: |
                  aws ec2 authorize-security-group-ingress \
                    --group-id ${{ secrets.AWS_SECURITY_GROUP }} \
                    --protocol tcp --port 22 \
                    --cidr ${{ env.runner_ip }}/32 > /dev/null 2>&1
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

            - name: Deploy Application on EC2
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.AWS_PROD_HOST }}
                  username: ${{ secrets.AWS_PROD_USERNAME }}
                  key: ${{ secrets.AWS_PROD_KEY_SSH }}
                  script: |
                      cd ~/kodus-web
                      ./start-web-app.sh prod ${{ env.IMAGE_TAG }} ${{ github.ref }}

            - name: Remove Runner IP from Security Group
              if: always()
              run: |
                  aws ec2 revoke-security-group-ingress \
                    --group-id ${{ secrets.AWS_SECURITY_GROUP }} \
                    --protocol tcp --port 22 \
                    --cidr ${{ env.runner_ip }}/32 > /dev/null 2>&1
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

            - name: Notify Discord on Success
              if: success()
              uses: sarisia/actions-status-discord@v1.13.0
              with:
                  webhook: ${{ secrets.DISCORD_WEBHOOK }}
                  status: ${{ job.status }}
                  content: ":tada: Deploy realizado com sucesso com a imagem `${{ env.IMAGE_TAG }}`!"
                  title: "Deploy Prod:"
